openapi: 3.0.0
info:
    title: Document Microservice API
    description: API for handling visit history in the document microservice
    version: 1.0.0
servers:
    - url: http://localhost:8083
      description: Local server

paths:
    /api/History/Account/{id}:
        get:
            summary: Get History of Visits for a specific account
            description: Retrieves the history of visits for a specific account based on their ID.
            tags:
                - History
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the account.
            responses:
                "200":
                    description: Successful response with the history of visits.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/History"
                "400":
                    description: Invalid ID supplied.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not doctor, user with this id.

    /api/History/{id}:
        get:
            summary: Get specific History entry
            description: Retrieves a specific history entry by its ID.
            tags:
                - History
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the history entry.
            responses:
                "200":
                    description: Successful response with the history entry.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/History"
                "400":
                    description: Invalid ID supplied.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not doctor, user with this id.

        put:
            summary: Update an existing History entry
            description: Updates an existing history entry by its ID.
            tags:
                - History
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the history entry to update.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateHistory"
            responses:
                "200":
                    description: History entry updated successfully.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: update success
                "400":
                    description: Invalid input.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin, manager, doctor and pacientId with role user.

    /api/History:
        post:
            summary: Create a new History entry
            description: Creates a new entry in the history.
            tags:
                - History
            security:
                - cookieAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateHistory"
            responses:
                "200":
                    description: History entry created successfully.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: create success
                "400":
                    description: Invalid input.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin, manager, doctor and pacientId with role user.

components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: accessToken
    schemas:
        History:
            type: object
            properties:
                ID:
                    type: integer
                    description: Unique identifier for the history entry.
                    example: 1
                date:
                    type: string
                    example: 2024-04-27T09:00:00Z
                    description: Date of the visit.
                pacientId:
                    type: integer
                    description: ID of the patient.
                    example: 123
                hospitalId:
                    type: integer
                    description: ID of the hospital.
                    example: 45
                doctorId:
                    type: integer
                    description: ID of the doctor.
                    example: 67
                room:
                    type: string
                    description: Room number or name.
                    example: "Room 101"
                data:
                    type: string
                    description: Additional data related to the visit.
                    example: "Patient diagnosed with flu."
        CreateHistory:
            type: object
            properties:
                date:
                    type: string
                    example: 2024-04-27T09:00:00Z
                    description: Date of the visit.
                pacientId:
                    type: integer
                    description: ID of the patient.
                    example: 123
                hospitalId:
                    type: integer
                    description: ID of the hospital.
                    example: 45
                doctorId:
                    type: integer
                    description: ID of the doctor.
                    example: 67
                room:
                    type: string
                    description: Room number or name.
                    example: "Room 101"
                data:
                    type: string
                    description: Additional data related to the visit.
                    example: "Patient diagnosed with flu."
security:
    - cookieAuth: []
