openapi: 3.0.0
info:
    title: Timetable Microservice API
    description: API for managing timetable and appointments in the timetable microservice.
    version: 1.0.0
servers:
    - url: http://localhost:8082
      description: Local server

paths:
    /api/Timetable:
        post:
            summary: Create a new timetable record
            description: Creates a new timetable record for a doctor. Condition from < to 12 hours.
            tags:
                - Timetable
            security:
                - cookieAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateTimetable"
            responses:
                "200":
                    description: Timetable record created successfully.
                "400":
                    description: Invalid input.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager.

    /api/Timetable/{id}:
        put:
            summary: Update an existing timetable record
            description: Updates an existing timetable record by its ID.
            tags:
                - Timetable
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the timetable record to update.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CreateTimetable"
            responses:
                "200":
                    description: Timetable record updated successfully.
                "400":
                    description: Invalid input or timetable has appointments.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager.

        delete:
            summary: Delete a timetable record
            description: Deletes a timetable record by its ID.
            tags:
                - Timetable
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the timetable record to delete.
            responses:
                "200":
                    description: Timetable record deleted successfully.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager.

    /api/Timetable/Doctor/{id}:
        get:
            summary: Get timetable by doctor ID
            description: Retrieves the timetable for a specific doctor.
            tags:
                - Timetable
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the doctor.
                - name: from
                  in: query
                  required: true
                  schema:
                      type: string
                      example: 2024-04-27T09:00:00Z
                  description: Start date-time of the query period.
                - name: to
                  in: query
                  required: true
                  schema:
                      type: string
                      example: 2024-04-27T21:00:00Z
                  description: End date-time of the query period.
            responses:
                "200":
                    description: Successful response with the doctor's timetable.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Timetable"
                "400":
                    description: Invalid date format or id.
                "401":
                    description: Unauthorized.

        delete:
            summary: Delete timetable records for a doctor
            description: Deletes all timetable records associated with a specific doctor.
            tags:
                - Timetable
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the doctor.
            responses:
                "200":
                    description: Timetable records for doctor deleted successfully.
                "400":
                    description: invalid input id
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager.

    /api/Timetable/Hospital/{id}:
        get:
            summary: Get timetable by hospital ID
            description: Retrieves the timetable for a specific hospital.
            tags:
                - Timetable
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the hospital.
                - name: from
                  in: query
                  required: true
                  schema:
                      type: string
                      example: 2024-04-27T09:00:00Z
                  description: Start date-time of the query period.
                - name: to
                  in: query
                  required: true
                  schema:
                      type: string
                      example: 2024-04-27T21:00:00Z
                  description: End date-time of the query period.
            responses:
                "200":
                    description: Successful response with the hospital's timetable.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Timetable"
                "400":
                    description: Invalid date format or id.
                "401":
                    description: Unauthorized.

        delete:
            summary: Delete timetable records for a hospital
            description: Deletes all timetable records associated with a specific hospital.
            tags:
                - Timetable
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the hospital.
            responses:
                "200":
                    description: Timetable records for hospital deleted successfully.
                "400":
                    description: Invalid input id.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager.
    /api/Timetable/Hospital/{id}/Room/{room}:
        get:
            summary: Get timetable by id of Hospital and room of Hospital
            description: Get timetable by id of Hospital and room of Hospital
            tags:
                - Timetable
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the hospital.
                - name: room
                  in: path
                  required: true
                  schema:
                      type: string
                  description: The room in the hospitalId.
            responses:
                "200":
                    description: Timetable records in hospitalId and room.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Timetable"
                "400":
                    description: Invalid input id.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin or manager or doctor.
    /api/Timetable/{id}/Appointments:
        get:
            summary: Get all free appointments
            description: Get all free appointments
            tags:
                - Appointments
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the timetable.
            responses:
                "200":
                    description: all free ticket.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: 2024-04-27T19:30:00Z, 2024-04-27T20:00:00Z, 2024-04-27T20:30:00Z
                "400":
                    description: Invalid input id.
                "401":
                    description: Unauthorized.
        post:
            summary: Borrow a ticket
            description: Borrow a ticket in Timetable.
            tags:
                - Appointments
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the timetable.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BorrowAppointment"
            responses:
                "200":
                    description: Borrow a ticket in Timetable success.
                "400":
                    description: Invalid input id.
                "401":
                    description: Unauthorized.
    /api/Appointment/{id}:
        delete:
            summary: Delete a ticket
            description: Delete a ticket in Timetable.
            tags:
                - Appointments
            security:
                - cookieAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: The ID of the appointment.
            responses:
                "200":
                    description: Delete a ticket in Timetable success.
                "400":
                    description: Invalid input id.
                "401":
                    description: Unauthorized.
                "403":
                    description: You are not admin, manager, recording user.
components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: accessToken
    schemas:
        Timetable:
            type: object
            properties:
                id:
                    type: integer
                    description: ID of timetable.
                hospitalId:
                    type: integer
                    description: ID of the hospital.
                doctorId:
                    type: integer
                    description: ID of the doctor.
                from:
                    type: string
                    example: 2024-04-27T19:00:00Z
                    description: Start time of the timetable entry.
                to:
                    type: string
                    example: 2024-04-27T21:00:00Z
                    description: End time of the timetable entry.
                room:
                    type: string
                    description: Room in which the timetable is scheduled.
        CreateTimetable:
            type: object
            properties:
                hospitalId:
                    type: integer
                    description: ID of the hospital.
                doctorId:
                    type: integer
                    description: ID of the doctor.
                from:
                    type: string
                    example: 2024-04-27T19:00:00Z
                    description: Start time of the timetable entry.
                to:
                    type: string
                    example: 2024-04-27T21:00:00Z
                    description: End time of the timetable entry.
                room:
                    type: string
                    description: Room in which the timetable is scheduled.
        BorrowAppointment:
            type: object
            properties:
                time:
                    type: string
                    example: 2024-04-27T21:00:00Z
                    description: Scheduled time of the appointment.
security:
    - cookieAuth: []
